server:
  port: 8088
  http2:
    enabled: false
  http3:
    enabled: false
  ssl:
    enabled: false
  compression:
    enabled: true
    mime-types:
      - application/octet-stream
      - application/json
    min-response-size: 1024
    http2:
      enabled: true
    http3:
      enabled: true

spring:
  application:
    name: capnproto-poc

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.techishthoughts.capnproto: DEBUG
    org.springframework.web: INFO
    org.capnproto: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
