version: '3.8'

services:
  # Jackson POC Service
  jackson-poc:
    build:
      context: ./jackson-poc
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "8441:8441"  # SSL port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx4g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network

  # Protocol Buffers POC Service
  protobuf-poc:
    build:
      context: ./protobuf-poc
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
      - "8442:8442"  # SSL port
      - "9090:9090"  # gRPC port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx2g -Xms1g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network

  # Avro POC Service
  avro-poc:
    build:
      context: ./avro-poc
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
      - "8443:8443"  # SSL port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx4g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    depends_on:
      - kafka
      - schema-registry
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network

  # Kryo POC Service
  kryo-poc:
    build:
      context: ./kryo-poc
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
      - "8444:8444"  # SSL port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx4g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network



  # MessagePack POC Service
  msgpack-poc:
    build:
      context: ./msgpack-poc
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
      - "8446:8446"  # SSL port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx4g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network

  # Cap'n Proto POC Service
  capnproto-poc:
    build:
      context: ./capnproto-poc
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
      - "8447:8447"  # SSL port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx4g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network

  # Apache Thrift POC Service
  thrift-poc:
    build:
      context: ./thrift-poc
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
      - "8448:8448"  # SSL port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx4g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network



  # FST POC Service
  fst-poc:
    build:
      context: ./fst-poc
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
      - "8450:8450"  # SSL port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.math=ALL-UNNAMED --add-opens java.base/java.time=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED -Xmx4g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network

  # FlatBuffers POC Service
  flatbuffers-poc:
    build:
      context: ./flatbuffers-poc
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
      - "8451:8451"  # SSL port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx4g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network

  # gRPC POC Service
  grpc-poc:
    build:
      context: ./grpc-poc
      dockerfile: Dockerfile
    ports:
      - "8092:8092"
      - "8452:8452"  # SSL port
      - "9092:9092"  # gRPC port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx4g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network

  # CBOR POC Service
  cbor-poc:
    build:
      context: ./cbor-poc
      dockerfile: Dockerfile
    ports:
      - "8093:8093"
      - "8453:8453"  # SSL port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx2g -Xms1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8093/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network

  # BSON POC Service
  bson-poc:
    build:
      context: ./bson-poc
      dockerfile: Dockerfile
    ports:
      - "8094:8094"
      - "8454:8454"  # SSL port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx2g -Xms1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8094/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network

  # Apache Arrow POC Service
  arrow-poc:
    build:
      context: ./arrow-poc
      dockerfile: Dockerfile
    ports:
      - "8095:8095"
      - "8455:8455"  # SSL port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx4g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8095/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network

  # SBE POC Service
  sbe-poc:
    build:
      context: ./sbe-poc
      dockerfile: Dockerfile
    ports:
      - "8096:8096"
      - "8456:8456"  # SSL port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx2g -Xms1g -XX:+UseG1GC -XX:MaxGCPauseMillis=100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network

  # Apache Parquet POC Service
  parquet-poc:
    build:
      context: ./parquet-poc
      dockerfile: Dockerfile
    ports:
      - "8097:8097"
      - "8457:8457"  # SSL port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYSTORE_PASSWORD=changeit
      - JVM_OPTS=-Xmx4g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8097/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - serialization-network

  # Supporting Services

  # Redis for Kryo caching demos
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - serialization-network

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - serialization-network

  # Kafka for Avro demo
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - serialization-network

  # Schema Registry for Avro
  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - serialization-network

  # Monitoring and Observability

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - serialization-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - serialization-network

networks:
  serialization-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  kafka-data:
  redis-data:
  prometheus-data:
  grafana-data:
