// automatically generated by the FlatBuffers compiler, do not modify

package org.techishthoughts.flatbuffers;

@SuppressWarnings("unused")
public final class AddressType {
  private AddressType() { }
  public static final byte HOME = 0;
  public static final byte WORK = 1;
  public static final byte BILLING = 2;
  public static final byte SHIPPING = 3;

  public static final String[] names = { "HOME", "WORK", "BILLING", "SHIPPING", };

  public static String name(int e) { return names[e]; }
}

