// automatically generated by the FlatBuffers compiler, do not modify

package org.techishthoughts.flatbuffers;

@SuppressWarnings("unused")
public final class LanguageProficiency {
  private LanguageProficiency() { }
  public static final byte BEGINNER = 0;
  public static final byte INTERMEDIATE = 1;
  public static final byte ADVANCED = 2;
  public static final byte NATIVE = 3;

  public static final String[] names = { "BEGINNER", "INTERMEDIATE", "ADVANCED", "NATIVE", };

  public static String name(int e) { return names[e]; }
}

