// automatically generated by the FlatBuffers compiler, do not modify

package org.techishthoughts.flatbuffers;

@SuppressWarnings("unused")
public final class OrderStatus {
  private OrderStatus() { }
  public static final byte PENDING = 0;
  public static final byte CONFIRMED = 1;
  public static final byte SHIPPED = 2;
  public static final byte DELIVERED = 3;
  public static final byte CANCELLED = 4;

  public static final String[] names = { "PENDING", "CONFIRMED", "SHIPPED", "DELIVERED", "CANCELLED", };

  public static String name(int e) { return names[e]; }
}

