// automatically generated by the FlatBuffers compiler, do not modify

package org.techishthoughts.flatbuffers;

@SuppressWarnings("unused")
public final class PaymentMethod {
  private PaymentMethod() { }
  public static final byte CREDIT_CARD = 0;
  public static final byte DEBIT_CARD = 1;
  public static final byte PAYPAL = 2;
  public static final byte BANK_TRANSFER = 3;
  public static final byte CRYPTO = 4;

  public static final String[] names = { "CREDIT_CARD", "DEBIT_CARD", "PAYPAL", "BANK_TRANSFER", "CRYPTO", };

  public static String name(int e) { return names[e]; }
}

