// automatically generated by the FlatBuffers compiler, do not modify

package org.techishthoughts.flatbuffers;

@SuppressWarnings("unused")
public final class SkillLevel {
  private SkillLevel() { }
  public static final byte NOVICE = 0;
  public static final byte BEGINNER = 1;
  public static final byte INTERMEDIATE = 2;
  public static final byte ADVANCED = 3;
  public static final byte EXPERT = 4;

  public static final String[] names = { "NOVICE", "BEGINNER", "INTERMEDIATE", "ADVANCED", "EXPERT", };

  public static String name(int e) { return names[e]; }
}

