// automatically generated by the FlatBuffers compiler, do not modify

package org.techishthoughts.flatbuffers;

@SuppressWarnings("unused")
public final class SocialPlatform {
  private SocialPlatform() { }
  public static final byte FACEBOOK = 0;
  public static final byte TWITTER = 1;
  public static final byte LINKEDIN = 2;
  public static final byte INSTAGRAM = 3;
  public static final byte GITHUB = 4;

  public static final String[] names = { "FACEBOOK", "TWITTER", "LINKEDIN", "INSTAGRAM", "GITHUB", };

  public static String name(int e) { return names[e]; }
}

