// automatically generated by the FlatBuffers compiler, do not modify

package org.techishthoughts.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class UserProfile extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static UserProfile getRootAsUserProfile(ByteBuffer _bb) { return getRootAsUserProfile(_bb, new UserProfile()); }
  public static UserProfile getRootAsUserProfile(ByteBuffer _bb, UserProfile obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public UserProfile __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean mutateId(long id) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, id); return true; } else { return false; } }
  public String bio() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer bioAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer bioInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String avatarUrl() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer avatarUrlAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer avatarUrlInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String website() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer websiteAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer websiteInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String dateOfBirth() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dateOfBirthAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer dateOfBirthInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String gender() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer genderAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer genderInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String interests(int j) { int o = __offset(16); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int interestsLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }
  public StringVector interestsVector() { return interestsVector(new StringVector()); }
  public StringVector interestsVector(StringVector obj) { int o = __offset(16); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public org.techishthoughts.flatbuffers.Skill skills(int j) { return skills(new org.techishthoughts.flatbuffers.Skill(), j); }
  public org.techishthoughts.flatbuffers.Skill skills(org.techishthoughts.flatbuffers.Skill obj, int j) { int o = __offset(18); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int skillsLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public org.techishthoughts.flatbuffers.Skill.Vector skillsVector() { return skillsVector(new org.techishthoughts.flatbuffers.Skill.Vector()); }
  public org.techishthoughts.flatbuffers.Skill.Vector skillsVector(org.techishthoughts.flatbuffers.Skill.Vector obj) { int o = __offset(18); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public org.techishthoughts.flatbuffers.Education education(int j) { return education(new org.techishthoughts.flatbuffers.Education(), j); }
  public org.techishthoughts.flatbuffers.Education education(org.techishthoughts.flatbuffers.Education obj, int j) { int o = __offset(20); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int educationLength() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public org.techishthoughts.flatbuffers.Education.Vector educationVector() { return educationVector(new org.techishthoughts.flatbuffers.Education.Vector()); }
  public org.techishthoughts.flatbuffers.Education.Vector educationVector(org.techishthoughts.flatbuffers.Education.Vector obj) { int o = __offset(20); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public org.techishthoughts.flatbuffers.Language languages(int j) { return languages(new org.techishthoughts.flatbuffers.Language(), j); }
  public org.techishthoughts.flatbuffers.Language languages(org.techishthoughts.flatbuffers.Language obj, int j) { int o = __offset(22); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int languagesLength() { int o = __offset(22); return o != 0 ? __vector_len(o) : 0; }
  public org.techishthoughts.flatbuffers.Language.Vector languagesVector() { return languagesVector(new org.techishthoughts.flatbuffers.Language.Vector()); }
  public org.techishthoughts.flatbuffers.Language.Vector languagesVector(org.techishthoughts.flatbuffers.Language.Vector obj) { int o = __offset(22); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public org.techishthoughts.flatbuffers.SocialConnection socialConnections(int j) { return socialConnections(new org.techishthoughts.flatbuffers.SocialConnection(), j); }
  public org.techishthoughts.flatbuffers.SocialConnection socialConnections(org.techishthoughts.flatbuffers.SocialConnection obj, int j) { int o = __offset(24); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int socialConnectionsLength() { int o = __offset(24); return o != 0 ? __vector_len(o) : 0; }
  public org.techishthoughts.flatbuffers.SocialConnection.Vector socialConnectionsVector() { return socialConnectionsVector(new org.techishthoughts.flatbuffers.SocialConnection.Vector()); }
  public org.techishthoughts.flatbuffers.SocialConnection.Vector socialConnectionsVector(org.techishthoughts.flatbuffers.SocialConnection.Vector obj) { int o = __offset(24); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createUserProfile(FlatBufferBuilder builder,
      long id,
      int bioOffset,
      int avatarUrlOffset,
      int websiteOffset,
      int dateOfBirthOffset,
      int genderOffset,
      int interestsOffset,
      int skillsOffset,
      int educationOffset,
      int languagesOffset,
      int socialConnectionsOffset) {
    builder.startTable(11);
    UserProfile.addId(builder, id);
    UserProfile.addSocialConnections(builder, socialConnectionsOffset);
    UserProfile.addLanguages(builder, languagesOffset);
    UserProfile.addEducation(builder, educationOffset);
    UserProfile.addSkills(builder, skillsOffset);
    UserProfile.addInterests(builder, interestsOffset);
    UserProfile.addGender(builder, genderOffset);
    UserProfile.addDateOfBirth(builder, dateOfBirthOffset);
    UserProfile.addWebsite(builder, websiteOffset);
    UserProfile.addAvatarUrl(builder, avatarUrlOffset);
    UserProfile.addBio(builder, bioOffset);
    return UserProfile.endUserProfile(builder);
  }

  public static void startUserProfile(FlatBufferBuilder builder) { builder.startTable(11); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(0, id, 0L); }
  public static void addBio(FlatBufferBuilder builder, int bioOffset) { builder.addOffset(1, bioOffset, 0); }
  public static void addAvatarUrl(FlatBufferBuilder builder, int avatarUrlOffset) { builder.addOffset(2, avatarUrlOffset, 0); }
  public static void addWebsite(FlatBufferBuilder builder, int websiteOffset) { builder.addOffset(3, websiteOffset, 0); }
  public static void addDateOfBirth(FlatBufferBuilder builder, int dateOfBirthOffset) { builder.addOffset(4, dateOfBirthOffset, 0); }
  public static void addGender(FlatBufferBuilder builder, int genderOffset) { builder.addOffset(5, genderOffset, 0); }
  public static void addInterests(FlatBufferBuilder builder, int interestsOffset) { builder.addOffset(6, interestsOffset, 0); }
  public static int createInterestsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startInterestsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addSkills(FlatBufferBuilder builder, int skillsOffset) { builder.addOffset(7, skillsOffset, 0); }
  public static int createSkillsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSkillsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addEducation(FlatBufferBuilder builder, int educationOffset) { builder.addOffset(8, educationOffset, 0); }
  public static int createEducationVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEducationVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addLanguages(FlatBufferBuilder builder, int languagesOffset) { builder.addOffset(9, languagesOffset, 0); }
  public static int createLanguagesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startLanguagesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addSocialConnections(FlatBufferBuilder builder, int socialConnectionsOffset) { builder.addOffset(10, socialConnectionsOffset, 0); }
  public static int createSocialConnectionsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSocialConnectionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endUserProfile(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public UserProfile get(int j) { return get(new UserProfile(), j); }
    public UserProfile get(UserProfile obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

