server:
  port: 8095
  ssl:
    enabled: false

spring:
  application:
    name: arrow-serialization-poc
  profiles:
    active: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.techishthoughts.arrow: DEBUG
    org.springframework.web: INFO
    org.springframework.boot: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Apache Arrow Framework Configuration
arrow:
  framework:
    name: "Apache Arrow"
    version: "1.0.0"
    description: "Columnar in-memory format for big data and analytics"
    port: 8095
    ssl-port: 8455
