/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.techishthoughts.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Language extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3049658754611099079L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Language\",\"namespace\":\"org.techishthoughts.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"proficiency\",\"type\":{\"type\":\"enum\",\"name\":\"LanguageProficiency\",\"symbols\":[\"BASIC\",\"CONVERSATIONAL\",\"FLUENT\",\"NATIVE\"]}},{\"name\":\"isNative\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Language> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Language> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Language> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Language> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Language> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Language to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Language from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Language instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Language fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private java.lang.CharSequence name;
  private java.lang.CharSequence code;
  private org.techishthoughts.avro.model.LanguageProficiency proficiency;
  private boolean isNative;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Language() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param code The new value for code
   * @param proficiency The new value for proficiency
   * @param isNative The new value for isNative
   */
  public Language(java.lang.Long id, java.lang.CharSequence name, java.lang.CharSequence code, org.techishthoughts.avro.model.LanguageProficiency proficiency, java.lang.Boolean isNative) {
    this.id = id;
    this.name = name;
    this.code = code;
    this.proficiency = proficiency;
    this.isNative = isNative;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return code;
    case 3: return proficiency;
    case 4: return isNative;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: code = (java.lang.CharSequence)value$; break;
    case 3: proficiency = (org.techishthoughts.avro.model.LanguageProficiency)value$; break;
    case 4: isNative = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public java.lang.CharSequence getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.CharSequence value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'proficiency' field.
   * @return The value of the 'proficiency' field.
   */
  public org.techishthoughts.avro.model.LanguageProficiency getProficiency() {
    return proficiency;
  }


  /**
   * Sets the value of the 'proficiency' field.
   * @param value the value to set.
   */
  public void setProficiency(org.techishthoughts.avro.model.LanguageProficiency value) {
    this.proficiency = value;
  }

  /**
   * Gets the value of the 'isNative' field.
   * @return The value of the 'isNative' field.
   */
  public boolean getIsNative() {
    return isNative;
  }


  /**
   * Sets the value of the 'isNative' field.
   * @param value the value to set.
   */
  public void setIsNative(boolean value) {
    this.isNative = value;
  }

  /**
   * Creates a new Language RecordBuilder.
   * @return A new Language RecordBuilder
   */
  public static org.techishthoughts.avro.model.Language.Builder newBuilder() {
    return new org.techishthoughts.avro.model.Language.Builder();
  }

  /**
   * Creates a new Language RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Language RecordBuilder
   */
  public static org.techishthoughts.avro.model.Language.Builder newBuilder(org.techishthoughts.avro.model.Language.Builder other) {
    if (other == null) {
      return new org.techishthoughts.avro.model.Language.Builder();
    } else {
      return new org.techishthoughts.avro.model.Language.Builder(other);
    }
  }

  /**
   * Creates a new Language RecordBuilder by copying an existing Language instance.
   * @param other The existing instance to copy.
   * @return A new Language RecordBuilder
   */
  public static org.techishthoughts.avro.model.Language.Builder newBuilder(org.techishthoughts.avro.model.Language other) {
    if (other == null) {
      return new org.techishthoughts.avro.model.Language.Builder();
    } else {
      return new org.techishthoughts.avro.model.Language.Builder(other);
    }
  }

  /**
   * RecordBuilder for Language instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Language>
    implements org.apache.avro.data.RecordBuilder<Language> {

    private long id;
    private java.lang.CharSequence name;
    private java.lang.CharSequence code;
    private org.techishthoughts.avro.model.LanguageProficiency proficiency;
    private boolean isNative;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.techishthoughts.avro.model.Language.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.code)) {
        this.code = data().deepCopy(fields()[2].schema(), other.code);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.proficiency)) {
        this.proficiency = data().deepCopy(fields()[3].schema(), other.proficiency);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.isNative)) {
        this.isNative = data().deepCopy(fields()[4].schema(), other.isNative);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Language instance
     * @param other The existing instance to copy.
     */
    private Builder(org.techishthoughts.avro.model.Language other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.code)) {
        this.code = data().deepCopy(fields()[2].schema(), other.code);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.proficiency)) {
        this.proficiency = data().deepCopy(fields()[3].schema(), other.proficiency);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.isNative)) {
        this.isNative = data().deepCopy(fields()[4].schema(), other.isNative);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.techishthoughts.avro.model.Language.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.techishthoughts.avro.model.Language.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public org.techishthoughts.avro.model.Language.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public org.techishthoughts.avro.model.Language.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public org.techishthoughts.avro.model.Language.Builder setCode(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.code = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public org.techishthoughts.avro.model.Language.Builder clearCode() {
      code = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'proficiency' field.
      * @return The value.
      */
    public org.techishthoughts.avro.model.LanguageProficiency getProficiency() {
      return proficiency;
    }


    /**
      * Sets the value of the 'proficiency' field.
      * @param value The value of 'proficiency'.
      * @return This builder.
      */
    public org.techishthoughts.avro.model.Language.Builder setProficiency(org.techishthoughts.avro.model.LanguageProficiency value) {
      validate(fields()[3], value);
      this.proficiency = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'proficiency' field has been set.
      * @return True if the 'proficiency' field has been set, false otherwise.
      */
    public boolean hasProficiency() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'proficiency' field.
      * @return This builder.
      */
    public org.techishthoughts.avro.model.Language.Builder clearProficiency() {
      proficiency = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'isNative' field.
      * @return The value.
      */
    public boolean getIsNative() {
      return isNative;
    }


    /**
      * Sets the value of the 'isNative' field.
      * @param value The value of 'isNative'.
      * @return This builder.
      */
    public org.techishthoughts.avro.model.Language.Builder setIsNative(boolean value) {
      validate(fields()[4], value);
      this.isNative = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'isNative' field has been set.
      * @return True if the 'isNative' field has been set, false otherwise.
      */
    public boolean hasIsNative() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'isNative' field.
      * @return This builder.
      */
    public org.techishthoughts.avro.model.Language.Builder clearIsNative() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Language build() {
      try {
        Language record = new Language();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.code = fieldSetFlags()[2] ? this.code : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.proficiency = fieldSetFlags()[3] ? this.proficiency : (org.techishthoughts.avro.model.LanguageProficiency) defaultValue(fields()[3]);
        record.isNative = fieldSetFlags()[4] ? this.isNative : (java.lang.Boolean) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Language>
    WRITER$ = (org.apache.avro.io.DatumWriter<Language>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Language>
    READER$ = (org.apache.avro.io.DatumReader<Language>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.name);

    out.writeString(this.code);

    out.writeEnum(this.proficiency.ordinal());

    out.writeBoolean(this.isNative);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);

      this.proficiency = org.techishthoughts.avro.model.LanguageProficiency.values()[in.readEnum()];

      this.isNative = in.readBoolean();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 2:
          this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);
          break;

        case 3:
          this.proficiency = org.techishthoughts.avro.model.LanguageProficiency.values()[in.readEnum()];
          break;

        case 4:
          this.isNative = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










