/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.techishthoughts.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum LanguageProficiency implements org.apache.avro.generic.GenericEnumSymbol<LanguageProficiency> {
  BASIC, CONVERSATIONAL, FLUENT, NATIVE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LanguageProficiency\",\"namespace\":\"org.techishthoughts.avro.model\",\"symbols\":[\"BASIC\",\"CONVERSATIONAL\",\"FLUENT\",\"NATIVE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
