/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.techishthoughts.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum SocialPlatform implements org.apache.avro.generic.GenericEnumSymbol<SocialPlatform> {
  FACEBOOK, TWITTER, INSTAGRAM, LINKEDIN, GITHUB, YOUTUBE, TIKTOK, DISCORD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SocialPlatform\",\"namespace\":\"org.techishthoughts.avro.model\",\"symbols\":[\"FACEBOOK\",\"TWITTER\",\"INSTAGRAM\",\"LINKEDIN\",\"GITHUB\",\"YOUTUBE\",\"TIKTOK\",\"DISCORD\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
