server:
  port: 8097
  ssl:
    enabled: false

spring:
  application:
    name: parquet-serialization-poc
  profiles:
    active: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.techishthoughts.parquet: DEBUG
    org.springframework.web: INFO
    org.springframework.boot: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Apache Parquet Framework Configuration
parquet:
  framework:
    name: "Apache Parquet"
    version: "1.0.0"
    description: "Columnar storage format for data warehousing and analytics"
    port: 8097
    ssl-port: 8457
